# Generated by Django 3.2.5 on 2021-07-02 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=256)),
                ('school', models.CharField(max_length=256)),
                ('grade', models.CharField(choices=[('小3', '小3'), ('小4', '小4'), ('小5', '小5'), ('小6', '小6')], max_length=256)),
                ('lesson_count', models.IntegerField(default=0)),
                ('lesson_selected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=256)),
                ('school', models.CharField(max_length=256)),
                ('grade', models.CharField(choices=[('小3', '小3'), ('小4', '小4'), ('小5', '小5'), ('小6', '小6')], max_length=256)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.lesson')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.user')),
            ],
        ),
    ]
